# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Quor
site_url: https://docs.quor.dev
site_description: Documentation for Quor, a catalog of secure container images with zero or near-zero CVEs, digital signatures, and SBOMs for production-grade supply chain security.
site_author: Getup
copyright: Copyright &copy; Getup
nav:
  - About Quor: index.md
  - Internal architecture: internal-architecture.md
  - Getting started: getting-started.md
  - Image catalog: catalog.md
  - SBOM: sbom.md
  - VEX: vex.md
  - Image Subscriptions: subscriptions.md
  - Accounts and Plans: plans.md
  - Vulnerability Attributes: vulnerability-attributes.md
theme:
  name: material
  custom_dir: docs/overrides
  logo_light: assets/logo.svg
  logo_dark: assets/logo-dark.svg
  favicon: assets/favicon.svg
  language: en
  palette:
    - scheme: default
      primary: white
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: Documentation
        - locale: pt
          name: Português
          build: true
          site_name: Documentação
          nav_translations:
            About Quor: Sobre o Quor
            Internal architecture: Arquitetura interna
            Getting started: Começando
            Image catalog: Catálogo de imagens
            SBOM: SBOM
            VEX: VEX
            Image Subscriptions: Subscrições de imagens
            Accounts and Plans: Contas e planos
            Vulnerability Attributes: Atributos de uma vulnerabilidade
          admonition_translations:
            note: Nota
extra:
  generator: false
  analytics:
    provider: google
    property: G-Z2P72X4VM5
